export class Parteditmodel {

    // actionBy: number;
actionOn: Date;
applicableAccessory: string;
applicableDummyPlug: string;
applicableSeal: string;
applicableTerminal: string;
applicableWireRange: string;
bundleDia_W_H: string;
color: string;
comodity: string;
createdBy: number;
createdDate: string;
csa: string;
customerName: string;
customerPartNumber: string;
description: string;
detailID: number;
drawingTab: string;
gender: string;
grommetHardness:string;
height_mm: string;
hybrid: string;
id: number;
imageTab: string;
internalPartNumber: string;
isActive: boolean;
lDocumentList: string;
lastUpdatedBy: number;
lastUpdatedDate: Date;
lastUpdatedOn: Date;
length_mm: string;
material: string;
matingPart: string;
matingSupplierName: string;
matingSupplierPart:string;
maxTemp_degree:string;
minTemp_degree: string;
noOfPoles:string;
noOfStrands: string;
outside: string;
panelThickNess: string;
partNumber1: string;
partNumber2: string;
pinRowsLayout: string;
platingColor: string;
proposalID: string;
rank: string;
relatedPart:string;
remarks: string;
sealDia: string;
sealedUnSealed: string;
series: string;
status: string;
supplierName: string;
supplierPartNumber: string;
uom: string;
wallThickness_mm: string;
weight: string;
wholeSize: string;
width_mm: string;
wireInsulationDiaRange: string;
wireStandard: string;
yazakiPartNumber: string;
}
