export class PartMasterDownload {

ID:number;
YazakiPartNumber:string;
InternalPartNumber:string;
Comodity:string;
Description:string;
SupplierPartNumber:string;
SupplierName:string;
CustomerPartNumber:string;
CustomerName:string;
NoOfPoles:string;
PinRowsLayout:string;
SealedUnSealed:string;
Gender:string;
Series:string;
PlatingColor:string;
Color:string;
Material:string;
Hybrid:string;
Width_mm:string;
Length_mm:string;
Height_mm:string;
UOM:string;
MaxTemp_degree:string;
MinTemp_degree:string;
Outside:string;
ApplicableWireRange:string;
WireInsulationDiaRange:string;
CSA	:string;
NoOfStrands:string;
WallThickness_mm:string;
SealDia:string;
BundleDia_W_H:string;
WholeSize:string;
PanelThickNess:string;
ImageTab:string;
DrawingTab:string;
RelatedPart:string;
MatingPart:string;
Status:string;
Weight:string;
Rank:string;
//Remarks:string;
IsActive: boolean;
LastUpdatedBy: string;
LastUpdatedOn: Date;
ApplicableSeal:string;
ApplicableDummyPlug:string;
ApplicableAccessory:string;
MatingSupplierPart:string;
MatingSupplierName:string;
ApplicableTerminal:string;
GrommetHardness:string;
WireStandard:string; 

PartMasterDownload(){
    this.ID= null;
    this.YazakiPartNumber= null;
    this.InternalPartNumber= null;
    this.Comodity= null;
    this.Description= null;
    this.SupplierPartNumber= null;
    this.SupplierName= null;
    this.CustomerPartNumber= null;
    this.CustomerName= null;
    this.NoOfPoles= null;
    this.PinRowsLayout= null;
    this.SealedUnSealed= null;
    this.Gender= null;
    this.Series= null;
    this.PlatingColor= null;
    this.Color= null;
    this.Material= null;
    this.Hybrid= null;
    this.Width_mm= null;
    this.Length_mm= null;
    this.Height_mm= null;
    this.UOM= null;
    this.MaxTemp_degree= null;
    this.MinTemp_degree= null;
    this.Outside= null;
    this.ApplicableWireRange= null;
    this.WireInsulationDiaRange= null;
    this.CSA	= null;
    this.NoOfStrands= null;
    this.WallThickness_mm= null;
    this.SealDia= null;
    this.BundleDia_W_H= null;
    this.WholeSize= null;
    this.PanelThickNess= null;
    this.ImageTab= null;
    this.DrawingTab= null;
    this.RelatedPart= null;
    this.MatingPart= null;
    this.Status= null;
    this.Weight= null;
    this.Rank= null;
    //this.Remarks= null;
    this.IsActive= null;
    this.LastUpdatedBy= null;
    this.LastUpdatedOn= null;
    this.ApplicableSeal= null;
    this.ApplicableDummyPlug= null;
    this.ApplicableAccessory= null;
    this.MatingSupplierPart= null;
    this.MatingSupplierName= null;
    this.ApplicableTerminal= null;
    this.GrommetHardness= null;
    this.WireStandard= null;
        
    }
}