export class User {
  userRoleId: number;
  userId: string;
  dept_Code: number;
  role_Code: string;
  plant_Code: number;
  user_Name: string;
  id: number;
  title: string;
  accountName: string;
  firstName: string;
  lastName: string;
  name: string;
  workPhone: number;
  department: string;
  jobTitle: string;
  manager: string;
  userName: string;
  workMail: string;
  officeLocation: string;
  gradeCode: string;
  costCenter: string;
  costCenterCode: string;
  bankAccountNumber: string;
  pan: string;
  location: string;
  gender: string;
  passport: string;
  dob: Date;
  reportTo: string;
  phone: string;
  prid: string;
  // isLogin: boolean;
    User() {
      this.userRoleId = null;
      this.userId = null;
      this.dept_Code = null;
      this.role_Code = null;
      this.plant_Code = null;
      this.user_Name = null;
      this.id = null;
      this.title = null;
      // this.isLogin = false;
      this.accountName = null;
      this.firstName = null;
      this.lastName = null;
      this.name = null;
      this.workPhone = null;
      this.department = null;
      this.jobTitle = null;
      this.manager = null;
      this.userName = null;
      this.workMail = null;
      this.officeLocation = null;
      this.gradeCode = null;
      this.costCenter = null;
      this.costCenterCode = null;
      this.bankAccountNumber = null;
      this.pan = null;
      this.location = null;
      this.gender = null;
      this.passport = null;
      this.dob = null;
      this.reportTo = null;
      this.phone = null;
      this.prid = null;
    }
}
